### ISSUE TITLE
Update to 2.1

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix-ui-samples-2#8]
# Tasks:

- [x] Remove `codeEditor` theme change workaround jmix-framework/jmix#2046
- [x] Update `formLayout` sample, fix responsive steps jmix-framework/jmix#2201
- [x] Fix badges jmix-framework/jmix#2037
- [x] Declarativelly `html`  jmix-framework/jmix#1974
- [x] DataGrid aggregation sample jmix-framework/jmix#1754
- [x] DataGrid header-filter sample jmix-framework/jmix#1752
- [x] DataGrid multi-sort sample jmix-framework/jmix#1265
- [x] DataGrid declarative renderers jmix-framework/jmix#1177
- [x] ItemsFetchCallback sample  jmix-framework/jmix#1923
- [x] FlexLayout sample  jmix-framework/jmix#1611
- [x] TimerFacet jmix-framework/jmix#2106
- [x] VirtualList component jmix-framework/jmix#835
- [x] #6
- [x] Stable version in `build.gradle`
- [x] Code cleanup

# Later
- [x] ~~Maps samples jmix-framework/jmix#1985~~

# ???
- [x] ~~PrefixSuffix XML jmix-framework/jmix#2096~~
- [x] ~~Native CSS jmix-framework/jmix#2095~~

**Comment by KremnevDmitry** [comment]
Waiting for Release 2.1
Merge required
