### ISSUE TITLE
Implement jmix-flowui-sampler

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix-ui-samples-2#9]
Plan:

- [x] Stable App
- [x] SampleView
- [x] MainMenu
- [x] Anonymous access
- [x] ThemeToggle (partly)
- [x] Fix menu width
- [x] Fix Session expiration
- [x] Fix css file sources in production mode (badge icons)
- [ ] Add localization support
- [x] Components
    - [x] Avatar
    - [ ] Avatar Group [blocked by jmix-framework/jmix#1869]
    - [x] BigDecimalField
    - [x] Badge
    - [x] Button
    - [x] Checkbox
    - [x] Checkbox Group
    - [x] CodeEditor
    - [x] ComboBox
    - [x] ~ComboBoxPicker~
    - [x] Context Help + Tooltip
    - [x] DrowdownButton (ComboButton)
    - [x] ~CompositeComponent~
    - [x] DataGrid
    - [x] DatePicker (TimePicker, DateTimePikcer)
    - [x] EmailField
    - [x] EntityComboBox
    - [x] EntityPicker
    - [x] ~FileStorageUploadField~
    - [x] ~FileUploadField~
    - [x] GenericFilter
    - [x] Icons
    - [x] IntegerField
    - [x] Image
    - [x] ListBox (MultiSelectListBox) [add doc link soon]
    - [x] ~Label~
    - [x] MultiSelectComboBox (MultiSelectComboBoxPicker)
    - [x] NumberField
    - [x] PasswordField
    - [ ] Pagination [blocked by: jmix-framework/jmix#1152]
    - [x] ProgressBar
    - [x] PropertyFilter
    - [x] RadioButtonGroup
    - [x] Select
    - [x] SimplePagination
    - [x] Tabs
    - [x] TextArea
    - [x] TextField
    - [x] ~UploadField~
    - [x] ValuePicker (MultiValuePicker)
    - [x] Html components
    - [ ] VirtualList [blocked by jmix-framework/jmix#835]
- [x] Containers
    - [x] Accordion
    - [x] Details
    - [x] ~Drawer?~
    - [x] FormLayout
    - [x] HorizontalLayout
    - [x] Scroller
    - [x] Split
    - [x] TabSheet
    - [x] VerticalLayout
    - [x] ~Layout with shortcut?~
- [x] Dialogs and notifications
    - [x] Dialogs
    - [x] Notifications
- [x] Cookbook
- [x] ~Dashboard~
